### PR TITLE
chore: cleanup protocol var

### PR DESCRIPTION
**Pull request by chemelli74**

### CODE REVIEW

**Comment by rokam** [comment]
I'm afraid I have to disagree with this change.  That behavior was to prevent protocol v3 from being set as v2 or v1.
That was made to prevent user error

**Comment by chemelli74** [comment]
> I'm afraid I have to disagree with this change. That behavior was to prevent protocol v3 from being set as v2 or v1. That was made to prevent user error

Which user error can happen in the new code path ?

**Comment by rokam** [comment]
When the user uses discover and the device is version 3. The user can't change it to v1 or v2 manually. So it will require key and token

**Comment by chemelli74** [comment]
> When the user uses discover and the device is version 3. The user can't change it to v1 or v2 manually. So it will require key and token

New code force the usage of the device discover protocol so in this case forces v3.
I don't see the problem honestly.

**Review by rokam — APPROVED** [review]
You're right. My bad, I did miss the `protocol or ProtocolVersion` line

**Comment by picone** [comment]
> You're right. My bad, I did miss the `protocol or ProtocolVersion` line

I think there's a bug. If the `protocol` is set, it should be an int type and can not be iterable. Here's my error stack:

```txt
2024-10-08 18:06:48.079 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 128, in post
    result = self._prepare_result_json(result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 228, in _prepare_result_json
    return _prepare_config_flow_result_json(result, super()._prepare_result_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 135, in _prepare_config_flow_result_json
    return prepare_result_json(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 52, in _prepare_result_json
    data["data_schema"] = voluptuous_serialize.convert(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous_serialize/__init__.py", line 40, in convert
    pval = convert(value, custom_serializer=custom_serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous_serialize/__init__.py", line 91, in convert
    "options": [(item, item) for item in schema.container],
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not iterable
```

Once I modify the code to below, everything worked perfectly:

```py3
vol.Required(
    CONF_PROTOCOL,
    default=protocol or ProtocolVersion.V3,
): vol.In(
    ProtocolVersion,
),
```

**Comment by chemelli74** [comment]
https://github.com/wuwentao/midea_ac_lan/blob/6c325d7548c0f10353a821c796fb467907b7e877/custom_components/midea_ac_lan/config_flow.py#L848-L850

I think line L849 it's more:

```python
[protocol] or Protocol
```

Can you quickly test please ?

**Comment by picone** [comment]
> https://github.com/wuwentao/midea_ac_lan/blob/6c325d7548c0f10353a821c796fb467907b7e877/custom_components/midea_ac_lan/config_flow.py#L848-L850
> 
> I think line L849 is more:
> 
> ```python
> [protocol] or Protocol
> ```
> 
> Can you quickly test please ?

It works for my scenario. But there is another bug, the schema version is just showing "Unknown"

image

**Comment by chemelli74** [comment]
```python
[protocol] if protocol else Protocol
```

**Comment by picone** [comment]
> ```python
> [protocol] if protocol else Protocol
> ```

LGTM

**Comment by chemelli74** [comment]
> > ```python
> > [protocol] if protocol else Protocol
> > ```
> 
> LGTM

So you confirm it works as expected ?

**Comment by picone** [comment]
> So you confirm it works as expected ?

Yes, please update it.

**Pull request merged**
