### PR TITLE
feat(c3): silent level

### PR DESCRIPTION
**Pull request by rokam**
Fixes: #80

### CODE REVIEW

**Comment by erikgieseler** [comment]
I have tested setting the corresponding levels, works as intended. 
However, after restarting HA, the Silent_Level field is not filled. It does not show the current level.
Screenshot
[_homeassistant_logs.txt](https://github.com/user-attachments/files/16570413/_homeassistant_logs.txt)

**Comment by rokam** [comment]
Did you bump lib to 2.6.2?

**Comment by erikgieseler** [comment]
> Did you bump lib to 2.6.2?

Yes
Manifest

**Comment by rokam** [comment]
I see the issue this should fix: https://github.com/rokam/midea-local/pull/270

**Review by wuwentao — APPROVED** [review]

**Comment by rokam** [comment]
@wuwentao we need to wait for https://github.com/rokam/midea-local/pull/270 before publishing it.

**Pull request merged**
