### PR TITLE
fix: avoid updates during shutdown

### PR DESCRIPTION
**Pull request by chemelli74**

### CODE REVIEW

**Review by wuwentao — COMMENTED** [review]
sorry, I'm not fully understand it.
anyway, is this possible to merge `if self.hass.is_stopping` and `if not self.hass` ?
if not possible, maybe we still can add a error or warning debug log in `self.hass.is_stopping`

**Comment by rokam** [comment]
I do agree with @wuwentao 
You need to check `self.hass` first

**Comment by wuwentao** [comment]
> update is called by core, so hass is there at the time of invocation. It cannot happen it's not

No, I can certainly confirm that:

```
if not self.hass:
            _LOGGER.error(
                "Midea entity update_state for %s [%s] with status %s",
```
it has been matched in my device error log, 
but I'm not enable the debug log,  only one line error log exist, so I can't find out the root cause when this error exist.

**Comment by chemelli74** [comment]
There must be a issue, probably a thread issue, as update cannot be called if hass is None.

I'll add a check, but with a note that we need to investigate.

**Review by rokam — APPROVED** [review]
LGTM

**Pull request merged**
