### PR TITLE
Feature/deattach-lib

### PR DESCRIPTION
**Pull request by rokam**
Migrate midea folder to a external library midea-local

### CODE REVIEW

**Comment by rokam** [comment]
@wuwentao this should work. I did a test with my AC unit. Due to this being a big change, it should be better tested before merging.

**Comment by wuwentao** [comment]
yes, it should be a big changes, we need more user and device to test and confirm  before merge it.
I have mark it as draft to flag it, once we can confirmed it , we can merge it later.

**Comment by wuwentao** [comment]
@attilaersek @Necroneco @chemelli74 @Qianli-Ma 

Hi my friends,

any suggestion or comments?  rokam has finished this midea-local lib and try to merge it.

1. can we help rokam to test with it? and confirm our test device and test result?  I will try to do some test with my device later and share my result later. as my WAHIN air-conditioners has been power off more than 6 months now, and I need to clean all of them, then try to power on and test it later.

2. once this PR merged, most of the core feature will be migrate to rokam's [midea-local](https://github.com/rokam/midea-local) repo, so there will be new  feature/issue exist in [midea-local](https://github.com/rokam/midea-local) repo and current repo, this repo will focus on hacs integration and midea-local will be focus on the core device feature support. 
we can  found issue/bug in any repo and try to fix it , hope we can continue improve it in future.

Thanks

**Comment by Necroneco** [comment]
I have tested on my `Water Drinking Appliance` yesterday, works as before.

**Comment by attilaersek** [comment]
looks good to me but give me a day or so to test it with my AC. I'll give a feedback quickly.

**Comment by attilaersek** [comment]
> looks good to me but give me a day or so to test it with my AC. I'll give a feedback quickly.

tested locally and works good, no errors or warnings in logs.

**Comment by attilaersek** [comment]
@rokam : resolved the conflict to help others testing the PR. if you have local changes pull the branch with `git pull --rebase` first.

**Comment by rokam** [comment]
Another strategy will be to create a beta release. Maybe with the actual branch.

**Comment by chemelli74** [comment]
> Another strategy will be to create a beta release. Maybe with the actual branch.

I would go that way honestly.
We easily make the user testing base larger.

**Comment by chemelli74** [comment]
Added [library_test.py](https://github.com/rokam/midea-local/pull/15) to the library to make testing easier.

I have a small authentication issue with new library + test script:

```
Traceback (most recent call last):
  File "/tmp/test.py", line 120, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/tmp/test.py", line 106, in main
    ac.authenticate()
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 165, in authenticate
    raise AuthException()
midealocal.device.AuthException

```

**Comment by Qianli-Ma** [comment]
> @attilaersek @Necroneco @chemelli74 @Qianli-Ma
> 
> Hi my friends,
> 
> any suggestion or comments? rokam has finished this midea-local lib and try to merge it.
> 
> 1. can we help rokam to test with it? and confirm our test device and test result?  I will try to do some test with my device later and share my result later. as my WAHIN air-conditioners has been power off more than 6 months now, and I need to clean all of them, then try to power on and test it later.
> 2. once this PR merged, most of the core feature will be migrate to rokam's [midea-local](https://github.com/rokam/midea-local) repo, so there will be new  feature/issue exist in [midea-local](https://github.com/rokam/midea-local) repo and current repo, this repo will focus on hacs integration and midea-local will be focus on the core device feature support.
>    we can  found issue/bug in any repo and try to fix it , hope we can continue improve it in future.
> 
> Thanks

I'll test with my Colmo central AC this weekend. I'll have more free time by the end of May.

**Comment by wuwentao** [comment]
> > Another strategy will be to create a beta release. Maybe with the actual branch.
> 
> I would go that way honestly. We easily make the user testing base larger.

got it, I will test current changes with my devices this weekend and share the test result.
then we can merge current PR next week.

**Comment by rokam** [comment]
> Added [library_test.py](https://github.com/rokam/midea-local/pull/15) to the library to make testing easier.
> 
> I have a small authentication issue with new library + test script:
> 
> ```
> Traceback (most recent call last):
>   File "/tmp/test.py", line 120, in <module>
>     asyncio.run(main())
>   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/tmp/test.py", line 106, in main
>     ac.authenticate()
>   File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 165, in authenticate
>     raise AuthException()
> midealocal.device.AuthException
> ```

authenticate only works with v3 devices.

**Comment by chemelli74** [comment]
> authenticate only works with v3 devices.

https://github.com/rokam/midea-local/pull/15#discussion_r1614668090

**Comment by wuwentao** [comment]
did a simple test, seems it works with My midea AC device, 
there is some PR about update the core device lib, we can merge this PR and move the core device feature to midea-local repo.

**Review by wuwentao — APPROVED** [review]

**Pull request merged**
