### PR TITLE
chore: bump midea-local to v4.0.0

### PR DESCRIPTION
**Pull request by chemelli74**
# PR Description

## Related issue

fix #X

### CODE REVIEW

**Review by rokam — APPROVED** [review]
LGTM

**Review by wuwentao — CHANGES_REQUESTED** [review]
sorry, we can't release v4.0.0 now, it should have the same socket issue like v3.0.1.
need a new version to fix it, please wait a moment.
I will commit/push the latest changes with device.py to fix it.

**Comment by chemelli74** [comment]
> sorry, we can't release v4.0.0 now, it should have the same socket issue like v3.0.1. need a new version to fix it, please wait a moment. I will commit/push the latest changes with device.py to fix it.

In the mean time we can bump library in the component. There is no release of the new component yet
Also note that v4.0.0 is already released ;-)

**Comment by chemelli74** [comment]
We should bump v4.0.0 as this is the version of the library that introduce the change in ProtocolVersion enum.
Then we wait for v4.0.1 before releasing the new component release.

**Pull request merged**
