### PR TITLE
fix: update python to python3 in myph.sh

### PR DESCRIPTION
**Pull request by wuwentao**
# PR Description
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 127

scripts/mypy.sh: line 7: python: command not found
```

## Related issue

fix #X

### CODE REVIEW

**Review by Necroneco — APPROVED** [review]

**Comment by chemelli74** [comment]
Again something strange, `python` should be a symlink to the latest python available in the system

**Comment by chemelli74** [comment]
After #170 , is that still needed ?

**Review by chemelli74 — CHANGES_REQUESTED** [review]
After https://github.com/wuwentao/midea_ac_lan/pull/170 , is that still needed ?

**Comment by wuwentao** [comment]
> Again something strange, `python` should be a symlink to the latest python available in the system

just for discussion:
most of the os don't have python symlink to python3, for example: ubuntu/debian/macos
as default `python` is python2 in old os and only use python3.

**Comment by chemelli74** [comment]
> > Again something strange, `python` should be a symlink to the latest python available in the system
> 
> just for discussion: most of the os don't have python symlink to python3, for example: ubuntu/debian/macos as default `python` is python2 in old os and only use python3.

_The correct way is sudo apt install python-is-python3 - it effectively does a symlink, but it also keeps pace with future updates; so if your ubuntu distribution moves to say Python 3.9, the manual symlink will no longer work, but the package makes sure it is still valid._

**Pull request closed without merging**
