### PR TITLE
feat(AC): support `current_humidity` for  AC device `climate`

### PR DESCRIPTION
**Pull request by semyonchetvertnyh**
# PR Description

Support `current_humidity` for `climate`

Screenshot 2024-12-07 at 23 04 54

### CODE REVIEW

**Comment by semyonchetvertnyh** [comment]
I'm not sure enough is it enough to work like in the screenshot, but I could make additional changes if needed.

**Comment by wuwentao** [comment]
this `current_humidity` add to base Climate class, so it will works for all the AC/CC/CF/C3/FB/etc Climate device.....
I'm not sure with most of these types devices should have or support a `indoor_humidity` sensor attribute, and it may can 't provide this attribute data for it, anyway, maybe default value None can be instead.

**Comment by semyonchetvertnyh** [comment]
Sure! Is it ok now?

**Review by chemelli74 — APPROVED** [review]
LGTM!

**Review by wuwentao — CHANGES_REQUESTED** [review]
sorry, you can't add this property to base class `MideaClimate`.
you can add it to `class MideaACClimate(MideaClimate)` as it will works for AC device.

the reason:
as base class will be call for all the climate device, but only AC device support `indoor_humidity`, for example, like FB/C3/CC/CF device, these device don't have attribute `indoor_humidity`, so we can't add it in base class.

just add it in the same file, but move it under class name `class MideaACClimate(MideaClimate)`

Thanks

**Comment by wuwentao** [comment]
> Sure! Is it ok now?

it's not the expected result.

`class MideaACClimate(MideaClimate)` start from line 255, you should add your code under `class MideaACClimate(MideaClimate)`

current code still in line 160 in base class `MideaClimate`

**Comment by semyonchetvertnyh** [comment]
No problem, I moved it from base class.

**Review by wuwentao — APPROVED** [review]

**Comment by wuwentao** [comment]
> No problem, I moved it from base class.

thanks, approved and merged.

**Comment by fabiobaleizao91** [comment]
Is there any way to force this setting to be enabled/disabled?
My AC's doesn't not have humidity sensor hence it's showing 0% all the time.
I wanted to be able to hide the humidity  from my HA card:
image

I was able to achieve that by commenting the lines added on the climate.py file:
image

However, I am wondering about the future updates, as the file will get updated and humidity must be showing up again. Is there any way to prevent this? I was thinking on customizing the HA card to not display the humidity info but I am unsure how to do it.

Thank you in advance.

**Comment by wuwentao** [comment]
@fabiobaleizao91  thanks for your info.
as `indoor_humidity` is extra sensor, so we can configure this device and remove it from extra sensor.
then it should ok for you.

**Comment by fabiobaleizao91** [comment]
> @fabiobaleizao91 thanks for your info. as `indoor_humidity` is extra sensor, so we can configure this device and remove it from extra sensor. then it should ok for you.

Thanks for your reply. How can I do that in the right way?

**Comment by wuwentao** [comment]
@fabiobaleizao91 just follow readme document, configure this device, disable `indoor humidty` in extra sensor list.
you should manual enabled it when you setup this device, so just disable it, it's enough.

**Comment by fabiobaleizao91** [comment]
> @fabiobaleizao91 just follow readme document, configure this device, disable `indoor humidty` in extra sensor list. you should manual enabled it when you setup this device, so just disable it, it's enough.

Got it! Thank you so much 🙌

**Comment by wuwentao** [comment]
@fabiobaleizao91 sorry, missed one important info: after disable this extra sensor, you still need to reboot HA to take effect.

**Comment by fabiobaleizao91** [comment]
> @fabiobaleizao91 sorry, missed one important info: after disable this extra sensor, you still need to reboot HA to take effect.

It was already disabled:
image

However, I ticket the indoor_humidity, unticked back, saved and reloaded the entity.. and stopped showing the humidity indeed:
image
No more humidity showing.

But will reboot HA as well. Thank you so much

**Pull request merged**
